-- Create ai_processed_bills table
CREATE TABLE IF NOT EXISTS public.ai_processed_bills (
    id integer NOT NULL DEFAULT nextval('ai_processed_bills_id_seq'::regclass),
    content_hash character varying NOT NULL UNIQUE,
    vendor_name character varying NOT NULL,
    canonical_vendor_name character varying,
    vendor_id character varying,
    total_amount numeric NOT NULL,
    subtotal numeric,
    tax_amount numeric,
    discount_amount numeric,
    currency character varying DEFAULT 'USD'::character varying,
    bill_number character varying,
    bill_date date NOT NULL,
    due_date date,
    po_number character varying,
    service_period_start date,
    service_period_end date,
    original_file_id character varying,
    original_file_name character varying,
    file_mime_type character varying,
    bill_data jsonb NOT NULL,
    ai_insights jsonb,
    classification_data jsonb,
    embeddings jsonb,
    overall_confidence numeric CHECK (overall_confidence >= 0::numeric AND overall_confidence <= 1::numeric),
    ai_extraction_confidence numeric CHECK (ai_extraction_confidence >= 0::numeric AND ai_extraction_confidence <= 1::numeric),
    vendor_confidence numeric CHECK (vendor_confidence >= 0::numeric AND vendor_confidence <= 1::numeric),
    account_confidence numeric CHECK (account_confidence >= 0::numeric AND account_confidence <= 1::numeric),
    location_confidence numeric CHECK (location_confidence >= 0::numeric AND location_confidence <= 1::numeric),
    processing_recommendation character varying CHECK (processing_recommendation::text = ANY (ARRAY['auto_process'::character varying, 'quick_review'::character varying, 'manual_review'::character varying]::text[])),
    auto_processed boolean DEFAULT false,
    requires_manual_review boolean DEFAULT false,
    vendor_type character varying,
    service_type character varying,
    is_recurring boolean DEFAULT false,
    urgency_level character varying CHECK (urgency_level::text = ANY (ARRAY['Low'::character varying, 'Medium'::character varying, 'High'::character varying, 'Overdue'::character varying]::text[])),
    anomaly_flags jsonb,
    qbo_bill_id character varying,
    qbo_vendor_ref character varying,
    qbo_uploaded_at timestamp without time zone,
    qbo_upload_status character varying DEFAULT 'pending'::character varying,
    processing_status character varying DEFAULT 'extracted'::character varying CHECK (processing_status::text = ANY (ARRAY['extracted'::character varying, 'classified'::character varying, 'approved'::character varying, 'uploaded'::character varying, 'rejected'::character varying]::text[])),
    processing_notes text,
    reviewed_by character varying,
    reviewed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_processed_bills_pkey PRIMARY KEY (id)
);

-- Add table comment
COMMENT ON TABLE public.ai_processed_bills IS 'AI-processed bill data with extraction results and classifications';